<html>
<head>
    <title>fm</title>
    <meta http-equiv="content-type" content="text/html">
</head>
<body>
<main>
    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="get">
        <select onchange="this.form.submit()" name="tz">
            <?php foreach (DateTimeZone::listIdentifiers() as $tz) : ?>
                <option value="<?php echo $tz ?>">
                    <?php echo $tz ?>
                </option>
            <?php endforeach ?>
        </select>
    </form>
</main>
</body>
</html>